### ISSUE TITLE
Add typing when reading EC expressions.

### ISSUE THREAD

**Issue by lio-wong** [hans/pyccg#4]
https://github.com/hans/pyccg/blob/0de3e6a7805c79506bdb2a1ec9e8f151f71886d3/pyccg/logic.py#L2165

Currently parses an EC-style S-expression into an untyped NLTK representation; iirc this could now read into *typed* expressions.

**Comment by hans** [comment]
Should be an easy fix; I can do it tomorrow.

Catherine Wong <notifications@github.com> schrieb am Do., 27. Juni 2019,
16:12:
